id: IB55EB1A5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:47:22+00:00'
last_modified: '2022-06-08T09:53:46.326433+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W15590
  title: བཤད་རྒྱུད་ཀྱི་འགྲེལ་པ་བདུད་རྩིའི་ཆུ་རྒྱུན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5F37:
      image_group_id: I1PD380
      title: ''
      total_pages: 656
      order: 1
      base_file: 5F37.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
