id: P009280
initial_creation_type: ocr
source_metadata:
  id: bdr:W15590
  title: བཤད་རྒྱུད་ཀྱི་འགྲེལ་པ་བདུད་རྩིའི་ཆུ་རྒྱུན
  author: ''
  volumes:
    d98837e9f09141b49acba669ec46e1ff:
      image_group_id: I1PD380
      title: ''
      volume_number: 1
      total_pages: 656
      base_file: v001.txt
